version: "3.9"

services:
  backend:
    image: tamirvlad/medapiback:latest
    container_name: backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    image: tamirvlad/medapifront:latest
    container_name: frontend
    ports:
      - "5174:80"
    restart: unless-stopped
    depends_on:
      - backend
